spring:
  profiles:
    active: dev
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8888


#spring:
#  application:
#    name: user-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        username: nacos
#        password: nacos
#
